### ISSUE TITLE
Typedef warnings with Haxe 4.0.5

### ISSUE THREAD

**Issue by zommerfelds** [okawa-h/js-firebase-extern#1]
Hi, I'm getting a bunch of warnings when compiling this library with Haxe 4.0.5

Example:
```
/home/gitpod/haxelib/js-firebase/0,2,0/firebase/database/Reference.hx:20: characters 53-69 : Warning : This typedef is deprecated in favor of js.lib.Promise<js.Promise.T>
```

I can try to change the type definitions if you are interested.

**Comment by okawa-h** [comment]
@zommerfelds 
Thank you for the issue!

I'm sorry, this library doesn't support Haxe 4.
I have no plans to repair it, so it would be helpful if you could give me a p-r!
